name: Build PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add --no-cache zsh
            zsh utility/compile.sh

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: build/main.pdf